"""add language to posts

Revision ID: 350f2f5ff03a
Revises: 4dc5c7ab8853
Create Date: 2022-07-06 13:56:42.927533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '350f2f5ff03a'
down_revision = '4dc5c7ab8853'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
